### ISSUE TITLE
timeCompare has a Java exception in toDateTime so thermostats are always reporting time out of date

### ISSUE THREAD

**Issue by wir3z** [dkilgore90/google-sdm-api#12]
In post events, this line can have the toDateTime removed, and it now functions fine:  timeCompare = (dataJson.timestamp).compareTo(lastEvent)

def postEvents() {
    logDebug('event received')
    def dataString = new String(request.JSON?.message.data.decodeBase64())
    logDebug(dataString)
    def dataJson = new JsonSlurper().parseText(dataString)
    def deviceId = dataJson.resourceUpdate.name.tokenize('/')[-1]
    def device = getChildDevice(deviceId)
    if (device != null) {
        def lastEvent = device.currentValue('lastEventTime')
        def timeCompare
        try {
            timeCompare = (dataJson.timestamp).compareTo(lastEvent)
        } catch (java.text.ParseException ignored) {
            //should only fail on first event -- e.g. lastEvent == null
        } 
        if ( timeCompare > 0 || lastEvent == null ) {
            sendEvent(device, [name: 'lastEventTime', value: dataJson.timestamp])  
            processTraits(device, dataJson.resourceUpdate)
        } else {
            log.warn("Received event out of order, refreshing device ${device}")
            getDeviceData(device)
        }
    }
}

**Comment by dkilgore90** [comment]
did you happen to capture the Java exception? I'm curious what it was throwing (possible other corner cases).

I wasn't sure about comparing the strings directly -- thus the `toDateTime` -- but if it works...

**Comment by wir3z** [comment]
The actual check always returned null, so the check always failed and it reported an out of sync warning.  When I tried to debug print each of the expressions, that is when I got the error.


I tried it with the todatetime removed, and it does work forward and back directly with no issues.


Lyle


________________________________
