### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by ispawnidie** [dkilgore90/google-sdm-api#16]
Making adjustment to temperature in Nest app or on thermostat itself does not update in Hubitat. Getting following error in logs: 

errorjava.lang.NullPointerException: null (postEvents)

**Comment by dkilgore90** [comment]
Is there a code line included with this NPE? If not, can you provide additional logs that surround it?

**Comment by ispawnidie** [comment]
No code line number.

`app:277 2020-10-07 09:18:58.825 pm error java.lang.NullPointerException: null (postEvents)
app:277 2020-10-07 09:18:58.819 pm debug {
  "eventId": "c597b3a1-1816-4ee6-8d63-1b288375904e",
  "timestamp": "2020-10-08T00:07:52.919Z",
  "resourceUpdate": {
    "name": "enterprises/0d10ebe0-737f-4a35-a7eb-6b0be8eef6ec/devices/AVPHwEviuuBw3ok4VfDeRkTII5ew8cYBcUW3eXIsGyUFe7mi7LLcWu_AntRxKgpbb6XGFgvzNakC93fIl61GMUYKHqIE5A",
    "traits": {
      "sdm.devices.traits.ThermostatMode": {
        "mode": "OFF",
        "availableModes": ["HEAT", "COOL", "HEATCOOL", "OFF"]
      },
      "sdm.devices.traits.ThermostatEco": {
        "availableModes": ["OFF", "MANUAL_ECO"],
        "mode": "OFF",
        "heatCelsius": 12.77776,
        "coolCelsius": 29.4444
      },
      "sdm.devices.traits.ThermostatTemperatureSetpoint": {
      }
    }
  },
  "userId": "AVPHwEs2Yn7LGwWQG-s8gpC1NTXI8KLxL_XXP59Pro63"
}
app:277 2020-10-07 09:18:58.812 pm debug event received`
