### ISSUE TITLE
Great work !!! Ability to write (execute) any of the traits yet?

### ISSUE THREAD

**Issue by clem2000** [dkilgore90/google-sdm-api#38]
Hi dkilgore90, wow this is great progress - been waiting for it a long time and fantastic to see how fare you already are.

When I check out the drivers, seems you already wrote code to execute against the traits (example Thermostat, set fan timer, etc.).
Can these already be executed out of Hubitat?

Thanks!

**Comment by dkilgore90** [comment]
Yes, the code to set thermostat traits is complete, and can be done directly via Hubitat. If you run into a problem, please file an issue here, or you can join the community discussion here: https://community.hubitat.com/t/pre-release-google-sdm-api-nest-integration/52226

**Comment by clem2000** [comment]
That`s great news.

Sorry for the stupid question, but how`d you add the tile to the dashboard to control it? When I select the Nest Thermostat and choose “Thermostat” it won`t work…  when working with “Attributes” I`ll only can read information?

Thank you!!!
-Clemens

**Comment by dkilgore90** [comment]
Questions and discussion continued in the community post, linked above.
