### ISSUE TITLE
feature: add support for hubitat package manager

### ISSUE THREAD

**Issue by aerickson** [dkilgore90/google-sdm-api#49]
I think it's just a metadata file that needs to be created. It makes updating 3rd-party apps really easy (WebCore uses it).

I'm happy to implement if you think it's a good idea.

https://community.hubitat.com/t/beta-hubitat-package-manager/38016

https://github.com/dcmeglio/hubitat-packagemanager
- https://github.com/dcmeglio/hubitat-packagemanager#developer-information

Thanks for your work on this project. :)

**Comment by dkilgore90** [comment]
Already implemented - it should be visible in HPM.

Admittedly I have a slightly different repo strategy than many devs - each app/driver set I'm developing has its own github repo, with a corresponding packageManifest.json file included. The repository.json file lives on its own, [here](https://github.com/dkilgore90/hpm-repo/blob/master/repository.json)
