### ISSUE TITLE
Remove lastEventTime from events

### ISSUE THREAD

**Issue by damunn** [dkilgore90/google-sdm-api#68]
I think the lastEventTime event is not needed, each event already has a time stamp.  I would suggest moving it to a device state.
Suggestion:
driver - remove
        attribute 'lastEventTime', 'string'
driver - append
def lastEventTime(String eventTime) {
	state.lastEventTime = eventTime
}
sdm app replace sendEvent(device, [name: 'lastEventTime', value: utcTimestamp.format("yyyy-MM-dd'T'HH:mm:ss.SSSXXX", location.timeZone)])
with:
 	device.lastEventTime(utcTimestamp.format("yyyy-MM-dd'T'HH:mm:ss.SSSXXX"))

**Comment by dkilgore90** [comment]
Interesting suggestion - I'm not against it. What's the motivation behind such a change? Cleaning up device attributes? Decreasing overall hub event throughput? Is there a performance improvement to using device state over events?

**Comment by damunn** [comment]
Someplace hubitat driver documentation said not to have extra device attributes that you wouldn't subscribe to.  When you look at the device event log, many of the entries are event time.  The event time is also on each attribute, so  this event is not needed.  I would imagine there is a little extra overhead reporting an event, but that wasn't the consideration. I would also move room and tempscale to device.state, as they are unlikely to change but they don't keep triggering more events.   The only downside to state is that rules can't examine them.  I couldn't find anyway to change an attribute without causing an event.  If there is a way, then I would leave them as attributes.   I suppose someone might want to use last event time to see if it is working.  That would be the only use I could think of. With the last event time removed it is a lot easier to see the thermostat operation in the event log.

**Comment by dkilgore90** [comment]
Makes sense -- likewise, I can't think of a user use case for this attribute.  Within the app, it is used to guarantee we are in sync with the actual device attributes, since Google doesn't guarantee event order -- I compare the incoming event timestamp against the lastEventTime, if it is earlier, then updates were out of order and I refresh all device attributes.  Looking back at it, though -- this is only needed for a Thermostat device, since the camera-based devices don't have any actual data updated by the events -- just sensor activations.

**Comment by damunn** [comment]
You can still do that with the date moved to state.  That kind of checking is being pretty thorough.  I wondered about the date checks.  Do you have any evidence that doing that has solved any problems?  I'm thinking that it would be extremely unlikely for the same attribute to be received out of order, since the frequency of changes is not that high - especially on the thermostat.  You definitely have done a fabulous job on this integration, especially considering the sparse documentation.

**Comment by dkilgore90** [comment]
Agree, I'm working on some of the new/changed items for the new devices - will move some of these to state instead of attributes in the next version

You're probably right - it's unlikely - just where my thoughts went when I saw that events out of order was possible.

**Comment by dkilgore90** [comment]
Completed in release 1.0.0 of app/drivers
