### ISSUE TITLE
Can we get motion information from the Device Access Console?

### ISSUE THREAD

**Issue by xihajun** [dkilgore90/google-sdm-api#72]
Thanks for you documentation

> A "Motion" event from Google will trigger a motion Active event in HE. Since the current API does not send another event when motion is no longer detected, a preferences entry is defined for each device, which determines the amount of time before the motion is deemed Inactive. If another motion event is received before this timer expires, the Inactive transition is deferred for the specified interval.

Dose this mean that we can capture a motion active event from google smart device?

**Comment by dkilgore90** [comment]
Yes, any Nest device with a camera (hello/doorbell, cam, or hub max) is compatible with the API, and Hubitat can recognize the motion events from them (and they can in turn be used as triggers for automations)
