### ISSUE TITLE
Outdoor Temperature

### ISSUE THREAD

**Issue by flesh420x** [dkilgore90/google-sdm-api#73]
Not sure if it's possible, but it would be nice if we could also get the Outdoor Temp that Nest reports. Being able to use this to automate eco mode in Rule Machine would be extremely nice.

**Comment by dkilgore90** [comment]
This data is not part of the API. My suspicion is that the Nest app aggregates this from another source based on your specified location - you could do the same by integrating a weather service (or more accurately, a local outdoor temp sensor) in Hubitat to drive some logic around your thermostat setPoints
