### ISSUE TITLE
Failed due to "client_secret" missing

### ISSUE THREAD

**Issue by ashenkin** [dkilgore90/google-sdm-api#79]
Hi there,
Got through most of the guide, but failed at the last step as I'm told that the client_secret is missing.  I tried putting it into the credentials.json, but no joy.  Any thoughts?
Thanks...
![2022-03-16 10_13_56-Hubitat Elevation - Google SDM API](https://user-images.githubusercontent.com/1608945/158649387-e4d832a7-e69e-4af7-aaad-b43007499de8.png)

**Comment by dkilgore90** [comment]
Cross-posting the answer from the Hubitat forum:

The `client_secret` key in the credentials.json should have a value provided by Google... Seems sometimes it doesn't export/download correctly - might try going to the Google cloud console, APIs, OAuth credentials, and download the JSON again.

**Comment by dkilgore90** [comment]
Resolved after re-downloading JSON
