### ISSUE TITLE
An unexpected error has occurred trying to load the app. 

### ISSUE THREAD

**Issue by Herrinc** [dkilgore90/google-sdm-api#92]
Trying to load Google sdm api
Unexpected r

**Comment by dkilgore90** [comment]
More info needed to diagnose - any additional errors displayed in the browser page? Error logs in the Hubitat logs?

**Comment by Herrinc** [comment]
(https://remoteaccess.aws.hubitat.com/logs#)groovy.json.internal.Exceptions$JsonInternalException: unexpected character r on line 198 (method uninstalled)
[app:910](https://remoteaccess.aws.hubitat.com/logs#)2023-01-15 11:25:18.364 AM[error](https://remoteaccess.aws.hubitat.com/logs#)groovy.json.internal.Exceptions$JsonInternalException: unexpected character r on line 198 (method mainPage)
[app:910](https://remoteaccess.aws.hubitat.com/logs#)2023-01-15 11:25:15.127 AM[error](https://remoteaccess.aws.hubitat.com/logs#)groovy.json.internal.Exceptions$JsonInternalException: unexpected character r on line 198 (method

**Comment by Herrinc** [comment]
[cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20230115_173645_Chrome_jpg_1673836374428]



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: dkilgore90 ***@***.***>
Date: 1/15/23 4:54 PM (GMT-07:00)
To: dkilgore90/google-sdm-api ***@***.***>
Cc: Herrinc ***@***.***>, Author ***@***.***>
Subject: Re: [dkilgore90/google-sdm-api] An unexpected error has occurred trying to load the app. (Issue #92)


More info needed to diagnose - any additional errors displayed in the browser page? Error logs in the Hubitat logs?

**Comment by Herrinc** [comment]
Sent from my Verizon, Samsung Galaxy smartphone
I have the project ID as seen below
What is entered in the credentials. Json field??


-------- Original message --------
From: dkilgore90 ***@***.***>
Date: 1/15/23 4:54 PM (GMT-07:00)
To: dkilgore90/google-sdm-api ***@***.***>
Cc: Herrinc ***@***.***>, Author ***@***.***>
Subject: Re: [dkilgore90/google-sdm-api] An unexpected error has occurred trying to load the app. (Issue #92)


More info needed to diagnose - any additional errors displayed in the browser page? Error logs in the Hubitat logs?

**Comment by dkilgore90** [comment]
Doing some cleanup and realized this ticket was still open -- sorry for the delay, are you still having issues?  Your screenshot did not attach successfully.

The project ID should be a UUID from the Device Access Project
The credentials.json is the full JSON object downloaded from your OAuth2 credentials in Google Cloud Project -- it appears that there is an unexpected character in your JSON which is causing the parsing to fail.

**Comment by dkilgore90** [comment]
Closing as this ticket has gone stale.
